### ISSUE TITLE
Supporting User Defined Datatypes

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaParallel/MPI.jl#120]
I would like to extend MPI.jl to allow users to create `MPI_Datatype`s for their custom `isbits` types and then be able to send/receive arrays of them.

Creating the new `MPI_Datatype` should be completely automated with the help of the `fieldoffsets`function in `Base`.  The problem is adding it to the list of known MPI datatypes.  It looks like MPI datatypes are currently defined using

```julia
    for (T,t) in _datatypes
        @eval mpitype(::Type{$T}) = $t
    end
```

where `_datatypes` is a `Dict` that maps from `DataType` to the MPI enum for the datatype.  The comments in the code indicate this is done because a `Dict` with `DataType` keys is not pre-compilable.  I can see two ways forward:

1. use `eval` inside the function that creates new `MPI_Datatypes` to add a new method to`mpitype` (I think  `eval` can be used on a nested function to add a method to a non-nested function, but I have not tested this yet)

2. create an `__init__` function and declare the dictionary inside it, which (should?) cause the hashing of the keys to happen at runtime.

I think the second would result in simpler code overall, eliminating the `mpitype` function in favor of directly accessing the dictionary, and be easier to extend.  This seems like the better approach to me, but I would like to get other peoples' thoughts before I put together a pull request.

**Comment by eschnett** [comment]
On Thu, Mar 31, 2016 at 3:52 PM, Jared Crean <notifications@github.com>
wrote:

> I would like to extend MPI.jl to allow users to create MPI_Datatypes for
> their custom isbits types and then be able to send/receive arrays of them.
>
> Creating the new MPI_Datatype should be completely automated with the
> help of the fieldoffsetsfunction in Base. The problem is adding it to the
> list of known MPI datatypes. It looks like MPI datatypes are currently
> defined using
>
>     for (T,t) in _datatypes
>         @eval mpitype(::Type{$T}) = $t
>     end
>
> where _datatypes is a Dict that maps from DataType to the MPI enum for
> the datatype. The comments in the code indicate this is done because a
> Dict with DataType keys is not pre-compilable. I can see two ways forward:
>
>    1.
>
>    use eval inside the function that creates new MPI_Datatypes to add a
>    new method tompitype (I think eval can be used on a nested function to
>    add a method to a non-nested function, but I have not tested this yet)
>    2.
>
>    create an __init__ function and declare the dictionary inside it,
>    which (should?) cause the hashing of the keys to happen at runtime.
>
> I think the second would result in simpler code overall, eliminating the
> mpitype function in favor of directly accessing the dictionary, and be
> easier to extend. This seems like the better approach to me, but I would
> like to get other peoples' thoughts before I put together a pull request.
>

I agree. In the initial implementation, defining functions for a few MPI
types made sense. At the moment, a dictionary seems like a better approach,
in particular since MPI calls are unlikely to be inlined.

-erik



-- 
Erik Schnetter <schnetter@gmail.com>
http://www.perimeterinstitute.ca/personal/eschnetter/

**Comment by JaredCrean2** [comment]
Cool, I will put together a pull request.

**Comment by JaredCrean2** [comment]
I need a bit of help getting the symbol names for `MPI_Type_create_struct` and `MPI_Type_commit` to be generated during installation.  I added them to `gen_constants.c`, but I think I also need to add the all capital letter name to `jlmpi_f2c.h`, but that seems to be auto generated as well, and I can't figure out from where.

My branch is [here](https://github.com/JaredCrean2/MPI.jl/tree/datatypes) if you want to look.

**Comment by eschnett** [comment]
You probably mean `get_functions.c` (not `constants`).

You need to add them to `CMakeLists.txt` as well.

I go with `find MPI -type f -print | xargs grep -ni MPI_INIT` to find all the places where `MPI_Init` is mentioned.

**Comment by JaredCrean2** [comment]
Edited `gen_constants.c` -> `get_functions.c`

That worked, thanks.

**Comment by JaredCrean2** [comment]
Another question: how to handle the `MPI_Aint` datatype (used for the `displacements` array argument of `MPI_Type_create_struct`)?  The man page for `MPI_Aint` says it is a C datatype, and therefore should not be used for the Fortran interface, but the Fortran interface does requires an 8 byte integer for that argument (on my system), rather than a regular `integer`.  I'm currently using `Csize_t` instead and that works for my system, but I don't know about portability.  I also can't find any documentation for the Fortran interface (to see if there is a correct Fortran datatype).

**Comment by eschnett** [comment]
You can look e.g. at OpenMPI's implementation of the Fortran routines; these come with Fortran modules that define all arguments. This is available online at <https://github.com/open-mpi/ompi-release/blob/v1.10/ompi/mpi/fortran/use-mpi-f08/type_create_struct_f08.F90>. Apparently the answer to your question is:
```Fortran
   INTEGER(MPI_ADDRESS_KIND), INTENT(IN) :: array_of_displacements(count)
```
But you may already know this.

In that case, using `Cptrdiff_t` -- the signed equivalent of `Csize_t` -- is probably the best one can do.

In addition, we could add a test that compares `sizeof(MPI_Aint)` and `sizeof(ptrdiff_t)`. Ideally, that test would be in a C file of its own, but if that's too complicated, it could also be added to `gen_functions.c`. The test would compare the sizes, and fail to compile if the sizes are different. Since `static_assert` might not be available, one of the substitutes is
```C
typedef int check_sizeof_MPI_Aint[sizeof(MPI_Aint) == sizeof(ptrdiff_t) ? 1 : -1];
```

**Comment by JaredCrean2** [comment]
Thanks, I updated the code and added the assert substitute of `gen_functions.c`.  Issuing pull request now.
