### ISSUE TITLE
Count arguments of `Scatterv` etc. should be `Int`, not `Cint`

### ISSUE THREAD

**Issue by eschnett** [JuliaParallel/MPI.jl#153]

**Comment by sloede** [comment]
As far as I can tell, this would require to internally convert the `counts` argument to a `Vector{Cint}`, since MPI uses `int`s for that (see also MPICH's [MPI_Scatterv](https://www.mpich.org/static/docs/v3.2.x/www3/MPI_Scatterv.html) documentation), adding a hidden run time and memory overhead. Maybe it could be an option to add a method that accepts an `AbstractVector{Integer}` (or something similar) for `counts` and converts it to the `Vector{Cint}` that MPI expects.

**Comment by simonbyrne** [comment]
This is handled now by `VBuffer` (#335).
