### ISSUE TITLE
Allreduce Broken on OSX

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaParallel/MPI.jl#163]
Testing [this](https://github.com/JuliaParallel/PETSc.jl/blob/fix_indexing/src/vec.jl#L389) section of code in Petsc.jl, I am getting a strange result from the Allreduce, but only on OSX.  The Travis log is [here](https://travis-ci.org/JuliaParallel/PETSc.jl/jobs/136995498), but the salient part of the log is:

```
process0Int(x.assembled) = 1
val = 1813
```

There is only one MPI process, so the `LAND` Allreduce of 1 should return 1.  Instead it returns what looks like uninitialized memory (`val` has been different for 2 different Travis runs).  I don't have access to an OSX machine, so I was hoping someone else would look into this.

**Comment by andreasnoack** [comment]
It could be an OpenMPI vs MPICH thing. It would probably be useful to set up OpenMPI testing on Linux as well. Be aware, though, that it's a bit painful because OpenMPI versions from the repos are ancient. Recently, I update the script in `MPI.jl` to download and build an up-to-date version of OpenMPI. See https://github.com/JuliaParallel/MPI.jl/blob/master/conf/travis-install-mpi.sh#L46-L53

**Comment by JaredCrean2** [comment]
It turns out OpenMPI does not support doing a logical and of `Int32` data, and for some reason Petsc was swallowing the error message.
