### ISSUE TITLE
Slow communication speed within machines, but fast speed between machines

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaParallel/MPI.jl#400]
Hi,

I use Julia to write MPI code and run it on multiple nodes on the server managed by SLURM via the script like this:
```
#SBATCH --nodes=5
#SBATCH --ntasks=5
#SBATCH --cpus-per-task=10

module load julia
srun julia mycode.jl
```

When I test the speed, the speed is fastest when there is only communication among nodes, and no communication within the node.

For example, using "3 nodes with 2 task-per-node" is much slower than using "6 nodes with 1 task-per-node".

But intuitively I feel the communication within a node should be faster than between node. So I want to ask whether this problem is caused by the nodes itself or by the Julia language? I'm considering to transform the Julia MPI code to C++, but I doubt this is helpless.

Thank you for your time during this difficult time,
Tianjing

**Comment by simonbyrne** [comment]
I don't see any reason it would have to do with Julia itself, it sounds more like an MPI library issue, or perhaps you're oversubscribing your nodes? Is it slower than the equivalent C++ code?

**Comment by simonbyrne** [comment]
One thing that would be good is to translate the [OSU Microbenchmarks](http://mvapich.cse.ohio-state.edu/benchmarks/) into Julia so that we could say for sure.

**Comment by zhaotianjing** [comment]
Thank you for your reply and suggestions.
I'm sure the nodes are not oversubscribed, and I don't have the equivalent C++ code yet.

**Comment by eschnett** [comment]
What does `mycode.jl` do? Can you add a pointer? Does it e.g. use linear algebra that would use multiple threads?

Did you check whether either MPI or Julia pins threads to cores, so that the OS would put all MPI processes onto a single core, leaving the others unused? Did you observe the job running `top` on one of the nodes?

How long does `mycode.jl` run? Is it seconds, minutes, or longer?

**Comment by zhaotianjing** [comment]
Hi, thank you for your reply.

The `mycode.jl` is running a for-loop, and in each step of the for-loop, there exists a matrix-vector multiplication coded as `c = A*b`. Here I think Julia utilizes multiple threads automatically.

I use `sbatch` to submit my job in multiples nodes, and when I go to one of them and run the `htop`, I did see multiple CPUs are running:

![image](https://user-images.githubusercontent.com/18593116/85183318-2369aa80-b240-11ea-8e7d-116ca4d5bf50.png)

I set a very small number of for-loop in `mycode.jl` because I just want to test the speed, so it only takes a few minutes.


Thank you,
Tianjing

**Comment by eschnett** [comment]
This might already explain your results. Since the multi-threading in Julia's linear algebra already keeps all cores busy, running more MPI processes on the same cores won't speed up things. Depending on scheduling, it might even slow down things. I would use a benchmark that does not use multiple threads. For example, you can set an environment variable to disable Julia's linear algebra multi-threading.

**Comment by simonbyrne** [comment]
Closing this for now. See #403 for the benchmarks.
