### ISSUE TITLE
Can't run on Julia file named "mpi.jl"

### ISSUE THREAD

**Issue by jgoldfar** [JuliaParallel/MPI.jl#41]
Not sure if this is a known issue, but it took an hour or so for me to debug (reinstalled MPI.jl & OpenMPI to check what was going on, stopped to work on something else, etc...)
Easy to reproduce (at least on OSX, with latest available OpenMPI available through Homebrew, and latest MPI.jl release, in julia 0.3.6): copy `examples/01-hello.jl` to `examples/mpi.jl`, and run it exactly as in the documentation: `mpirun -np 3 julia mpi.jl`.
side note: this has never come up for me running Julia on files with the same name as packages, but I suppose I could see how the issue could be related?

**Comment by lcw** [comment]
I think this has to do with they way julia imports modules and the case insensitivity (I am guessing because that is the default on Mac OS X) of your filesystem.  You can see at the top of each example there is a
```julia
import MPI
```
which I am guessing finds the `mpi.jl` file in your current directory.  This seems to happen even though the current directory is not in the variable `LOAD_PATH`.  I didn't see this behaviour in the julia [documentation](http://julia.readthedocs.org/en/latest/manual/modules/) so maybe that should be updated.
