### ISSUE TITLE
MPI tracing and profiling

### ISSUE THREAD

**Issue by vchuravy** [JuliaParallel/MPI.jl#444]
@simonbyrne and I tried yesterday to use `nsys` to debug an MPI program. They preload a wrapper library which doesn't work since we use `dlopen` directly. Once can hack around that, but a cleaner approach would be to use `Preferences.jl` to allow arbitrary instrumentation of https://github.com/JuliaParallel/MPI.jl/blob/502717a0f9aeb17eca38d73735322aadca317b19/src/implementations.jl#L3-L13

Since NVTX requires a library, and alternative would be NVTXT which I happen to have an implementation lying around https://github.com/JuliaGPU/KernelAbstractions.jl/commit/9852b766c5b777e600658fed60f0c9e06edb534b

**Comment by simonbyrne** [comment]
It would also be good to provide a way to support other MPI profilers which use `LD_PRELOAD` (which doesn't work with Julia as we `dlopen` the library directly). One idea would be something like [`@runtime_ccall`](https://github.com/JuliaGPU/CUDA.jl/blob/e3c714f238dc3de1675977b7a8e4aa64e6f1823b/lib/utils/call.jl#L15-L46) used by CUDA.jl, where we check if e.g. a library `ENV["JULIA_MPI_PRELOAD"]` exists and contains an appropriate symbol.

**Comment by richardreeve** [comment]
We’d be very keen on some more general support too as we’re trying to use extrae for some profiling and it also doesn’t work because it relies on LD_PRELOAD too...

**Comment by vchuravy** [comment]
@staticfloat any ideas for dealing with libraries that interpose with LD_PRELOAD?

**Comment by staticfloat** [comment]
So you need to `dlopen()` something else before you `dlopen()` the package you're interested in?

**Comment by vchuravy** [comment]
Yeah. We basically want to overlay/redirect lookups to a shim library.

**Comment by simonbyrne** [comment]
To clarify, MPI provides a specific profiling interface: the `MPI_XXX` function is just a wrapper around another function named `PMPI_XXX`. This allows profilers to export the `MPI_XXX` symbols via `LD_PRELOAD` which can do whatever they want, then call `PMPI_XXX`. See https://www.open-mpi.org/faq/?category=perftools#PMPI for a description on how Open MPI does this.

**Comment by staticfloat** [comment]
So is there a reason you can't just `dlopen()` whatever library you wish to override symbols with before you load `libmpi`?

**Comment by simonbyrne** [comment]
Wouldn't it still look up the symbols in libmpi?

**Comment by staticfloat** [comment]
It depends on how the lookups are being done.

If you have Julia code that's calling symbols, you should just change which library you are `dlsym()`'ing the symbols from.

If you have C code that is calling `foo()` and isn't explicitly dlsym'ing it from a particular library but is instead relying upon the dynamic linker to load the library and provide it the symbols, then yes, I would expect that `dlopen()`'ing some other library first that provides the `foo()` function would cause it to look up the `foo()` symbol in that other library.  If it doesn't work at first, make sure that `RTLD_GLOBAL` is passed in to `dlopen()`.

**Comment by lyon-fnal** [comment]
Ahh - this is an interesting issue! I had been trying to use [Darshan](https://www.mcs.anl.gov/research/projects/darshan/) to profile MPI and HDF5 i/o. Since is uses `LD_PRELOAD`, the issue here explains why it didn't work. It sounds like I can fix this by calling `dlopen(...)` on the darshan library before loading MPI and HDF5. Will try that!

**Comment by simonbyrne** [comment]
We may need to change all the `ccall`s, so that we call `ccall(:MPI_XXX,...)` instead of `ccall((:MPI_XXX, libmpi), ...)`

**Comment by lyon-fnal** [comment]
Hi - I have a simple minimum working example in [this gist](https://gist.github.com/lyon-fnal/e7e31452b82dc65e8fb9fbaa26022fb7). Indeed you'll have to change all `ccall` to just have the function and not specify the library. If your "injected" library does not wrap the original function with `dlsym(RTLD_NEXT, ...)` then I think you can `dlopen` the injected library before the `dlopen` for, say, `libmpi`. You must use `RTLD_GLOBAL` so that `ccall` can find the function without the library specification. If the injection library does wrap the original function (as darshan does) then you'll have to use `LD_PRELOAD=/path/to/inject.so julia myscript.jl`.

**Comment by simonbyrne** [comment]
I think that seems like the best way forward. Thanks @lyon-fnal for trying it out.

**Comment by lyon-fnal** [comment]
I was able to modify MPI.jl and HDF5.jl to use `ccall` without explicitly specifying the library (e.g. `ccall(:func, ...)` and not `ccall( (:func, lib), ...)`. With that, I'm able to get [Darshan](https://www.mcs.anl.gov/research/projects/darshan/) (MPI and HDF5 I/O profiler) to work with `LD_PRELOAD`. Pretty neat, though not as easy as I thought it would be. I'll open PRs for MPI.jl and HDF5.jl with my changes shortly. 

I'm contemplating what to tell the Julia developers about this ... using `ccall( (func, lib), ...)` as they suggest in the Julia docs is easy since you don't have to worry about loading the shared object yourself with `Libdl.dlopen`, but it does mean that `LD_PRELOAD` won't work. I know of several profiling systems that rely on `LD_PRELOAD`, so not having that capability is detrimental. May be nice if they at least have a warning about breaking `LD_PRELOAD`. Do you all have suggestions?

**Comment by simonbyrne** [comment]
Should be fixed by #451
