### ISSUE TITLE
Support for error handlers

### ISSUE THREAD

**Issue by calebwin** [JuliaParallel/MPI.jl#453]
It looks like MPI as early as 3.0 has error handling and it would be really awesome to have this supported in MPI.jl.

**Comment by simonbyrne** [comment]
It probably makes sense to at least try `MPI_ERRORS_RETURN` so that we can get nicer stacktraces, but I'm not sure it makes sense to use custom error handlers. For one thing, these require using callbacks, and in a multithreaded environment MPI might call the callback from a different thread, which [requires special handling on the Julia side](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Thread-safety).

The bigger problem is that MPI isn't generally fault tolerant. As the spec says:

> After an error is detected, the state of MPI is undefined. That is, using a user-defined error handler, or MPI_ERRORS_RETURN, does not necessarily allow the user to continue to use MPI after an error is detected. The purpose of these error handlers is to allow a user to issue user-defined error messages and to take actions unrelated to MPI (such as flushing I/O buffers) before a program exits. An MPI implementation is free to allow MPI to continue after an error but is not required to do so.

**Comment by simonbyrne** [comment]
Did you have a particular use case in mind?

**Comment by simonbyrne** [comment]
@calebwin can you look at #457? Would that be sufficient for your needs?

**Comment by calebwin** [comment]
Awesome! I looks like it would.

Thank you so much
