### ISSUE TITLE
New MPI implementation: MPItrampoline

### ISSUE THREAD

**Issue by eschnett** [JuliaParallel/MPI.jl#502]
This is more of a heads-up than an issue. I welcome feedback.

I have implemented a new MPI library [MPItrampoline](https://github.com/eschnett/MPItrampoline), which "implements" MPI by forwarding all calls at run time to a real MPI library. My goal is to make it easier for Yggdrasil to provide statically linked external libraries for Julia that work on HPC systems. This seems to work well. The last major missing piece of the puzzle is to make `MPI.jl` work with MPItrampoline as well.

The main problem is that MPItrampoline is initialized quite late, namely only when its shared library is loaded. This means e.g. that the various constants that MPI uses are only known at load time. This is explicitly allowed by the MPI standard (see e.g. MPI 3.1, section 2.5.4). It appears that MPItrampoline is the only MPI implementation that makes use of this, as I've had to submit pull requests to several other MPI-using packages.

In `MPI.jl`, my current solution is to store these constants (such as `MPI_INT`) in `global` variables instead of in `const` variables, and to set them when `MPI.jl` is initialized (via `__init__deps__`). An alternative choice would be to store these constants in `const Ref` objects, or in a `mutable struct` (essentially equivalent at the technical level). As consequence, these constants can also not be used as enum values (e.g. `@enum comparison`), and I had to convert the enums to structs – they now look similar to a handle. Other approaches are possible.

See https://github.com/eschnett/MPI.jl/tree/eschnett/mpitrampoline for current progress.

**Comment by sloede** [comment]
Wow, this seems like a very nice package that already supports quite a number of features!

Do I understand it correctly that for this to be used with BinaryBuilder/Yggdrasil, we'd have a workflow similar to this:
* Have an `MPItrampoline_jll` package that provides your main library
* Have various `MPIwrapper + X` JLL packages that wrap the existing MPI JLL packages in your auxiliary library, e.g., `OpenMPI_MPIwrapper_jll` (for a lack of better naming)
* Build MPI-enabled packages against `MPItrampoline_jll` instead of the various MPI implementations directly, e.g., `P4est_MPItrampoline_jll`
* Tell `MPI.jl` to use the `OpenMPI_MPIwrapper_jll` package as the MPI backend instead of `OpenMPI_jll` directly
* Don't see a difference to what we do now, except that I could also just use any host-installed MPI implementation as long as it is wrapped by `MPIwrapper` without having to recompile my `P4est_MPItrampoline_jll` package

I don't know about the others, but I think it would be great if you could introduce your package at the next Julia HPC call (which will take place next Tuesday, Aug 31st, I belive).

**Comment by vchuravy** [comment]
Thanks @eschnett! Can you briefly discuss the differences with wi4mpi?

**Comment by eschnett** [comment]
@sloede Almost:
- `MPIwrapper` would not be installed via JLLs. Instead, it is installed directly on the system where there is an existing MPI library, using `cmake`. This produces a `libmpiwrapper.so` file. When running an application that uses MPItrampoline, you need to set an environment variable to point to this `libmpiwrapper.so`.
- `MPI.jl` just uses `MPItrampoline_jll`. At run time, you choose which `libmpiwrapper.so` to use. There is no reconfiguring or rebuilding when a different real MPI library is used.
- If you want to use `OpenMPI_jll`, then you could point MPItrampoline to it. However, you might instead also just use `OpenMPI_jll` directly, since you wouldn't really benefit from MPItrampoline.

I'd be happy to introduce the package. This call is not on my calendar – do you have a pointer?

**Comment by giordano** [comment]
Fixed by  #513?
