### ISSUE TITLE
Libdl import errors

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/MPI.jl#54]
````

julia> using MPI
ERROR: LoadError: LoadError: UndefVarError: RTLD_LAZY not defined
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /Users/viral/.julia/v0.4/MPI/src/../deps/src/compile-time.jl, in expression starting on line 1
while loading /Users/viral/.julia/v0.4/MPI/src/MPI.jl, in expression starting on line 3


````

**Comment by ViralBShah** [comment]
This is with 0.4. There are other deprecations to fix too.

**Comment by dmbates** [comment]
I see that in January Amit changed `REQUIRE` line to
```
julia 0.4-
```
in the development version.  I was going to require `Compat` and change `RTLD_LAZY` to `@compat(Libdl.RTLD_LAZY)` etc., but if the development version is to be used only with 0.4- then the names could be preceded with `Libdl.` unconditionally.

Is it better to wrap with `@compat` or not?

**Comment by dmbates** [comment]
Upon further investigation it appears that the development version should be used with 0.4- only.  It would be good to note in `README.md` that installation via `Pkg.clone` followed by `Pkg.build` is a necessity with v0.4-.  If you first use `Pkg.add` then `Pkg.checkout` the tests will fail because the entire build will not be repeated.

In any case, the `Pkg.clone` followed by `Pkg.build` route worked for me on v0.4-
