### ISSUE TITLE
MPI_Init() seg fault on Summit

### ISSUE THREAD

**Issue by williamfgc** [JuliaParallel/MPI.jl#687]
I am getting a seg fault on Summit (it used to work following `MPIPreferences`) on `MPI_Init()`:

```
import MPI
MPI.Init()
```

```
signal (11): Segmentation fault
in expression starting at /gpfs/alpine/csc310/proj-shared/wgodoy/2022/hello_mpi/hello-mpi.jl:7
PMPI_Comm_set_errhandler at /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-8.3.1/spectrum-mpi-10.4.0.3-20210112-vgx3y6jjgccqihabnuasprb6pyqqfmal/lib/libmpi_ibm.so.3 (unknown line)
signal (11): Segmentation fault
...
MPI_Comm_set_errhandler at /ccs/home/wgodoy/.julia/packages/MPI/6bkWW/src/api/generated_api.jl:1512 [inlined]
set_errorhandler! at /ccs/home/wgodoy/.julia/packages/MPI/6bkWW/src/errhandler.jl:76 [inlined]
set_default_error_handler_return at /ccs/home/wgodoy/.julia/packages/MPI/6bkWW/src/errhandler.jl:35 [inlined]
#Init#30 at /ccs/home/wgodoy/.julia/packages/MPI/6bkWW/src/environment.jl:124
Init at /ccs/home/wgodoy/.julia/packages/MPI/6bkWW/src/environment.jl:81
unknown function (ip: 0x20002521ceef)
...
in expression starting at /gpfs/alpine/csc310/proj-shared/wgodoy/2022/hello_mpi/hello-mpi.jl:7
MPI_Comm_set_errhandler at /ccs/home/wgodoy/.julia/packages/MPI/6bkWW/src/api/generated_api.jl:1512 [inlined]
set_errorhandler! at /ccs/home/wgodoy/.julia/packages/MPI/6bkWW/src/errhandler.jl:76 [inlined]
MPIPreferences identify the system MPI just fine:
```

```
$ cat LocalPreferences.toml 
[MPIPreferences]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
libmpi = "libmpi_ibm"
mpiexec = "jsrun"
```

`spectrum-mpi` and `julia 1.8.2` modules are loaded. Any guidance is appreciated.

**Comment by giordano** [comment]
> Any guidance is appreciated.

A general recommendation for debugging this kind of crashes is to follow all the steps happening inside `MPI.Init()` to cook up a C program as close as possible to what Julia is doing internally.  For example, in https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1341698748 I found a small Julia code reproducing my crash and then I wrote [a somewhat similar C code](https://github.com/JuliaParallel/MPI.jl/issues/684#issuecomment-1341750277) (it's probably not 100% equivalent, but close enough) which is also crashing.  If I didn't do anything wrong in the translation, that's probably a good indication there are some problems with the MPI library itself I'm using, unrelated to Julia.

> (it used to work following `MPIPreferences`)

When you say "it used to work" you mean until a few days/weeks ago or what?  Do you remember what you changed since then?  Version of Julia/MPI.jl/MPIPreferences.jl/else?

**Comment by williamfgc** [comment]
@giordano @vchuravy thanks!

> When you say "it used to work" you mean until a few days/weeks ago or what?

Yes, I've been chasing the regression and things work with `julia/1.7.2`  using `MPI v0.20.5`, `MPIPreferences v0.1.7` . Strangely enough, it works with `julia/1.8.2` and I can't reproduce today.  My best guess is that something was messing with my module+julia environment, starting with `module purge` and `rm -r ~/.julia` might have helped. Thanks for your help. I'm closing this for now.

CC @PhilipFackler as we were able to reproduce the same results on Summit.
