### ISSUE TITLE
Implement cooperative test

### ISSUE THREAD

**Issue by luraess** [JuliaParallel/MPI.jl#762]
Seems it would be desired to have ` cooperative_test!` as part of MPI.jl (cc @vchuravy)

Where would it make sense to be added to within MPI.jl

Code would be close to:
```julia
function cooperative_test!(req)
    done = false
    while !done
        done, _ = MPI.Test(req, MPI.Status)
        yield()
    end
end
```

**Comment by luraess** [comment]
@giordano any hint on where to place this one? 🙏

**Comment by lcw** [comment]
I am not certain this function should be in MPI.jl.  I am curious what others think.

**Comment by luraess** [comment]
> I am not certain this function should be in MPI.jl. I am curious what others think.

Unsure either - it was @vchuravy 's suggestion. I could happily have it hosted elsewhere as well.

**Comment by simonbyrne** [comment]
What it sounds like you want (and what I also want) is an `MPI.Wait` that acts like `Base.wait` (i.e. will yield to other Julia tasks while blocking). Since MPI doesn't provide an interface for calling back into task-based runtimes, there are two basic approaches:
1. spin loop with `MPI.Test` and `yield()` (as is proposed here)
2. put the `MPI.Wait` on a separate thread (as I proposed in #452) (either a Julia thread or a libuv thread), and notify once it is done.

You can also use a hybrid of the two. e.g. here is what CUDA.jl does for stream/device synchronization:
https://github.com/JuliaGPU/CUDA.jl/blob/08f9c3da46fc5814406cd04c7d4701e641d1722c/lib/cudadrv/synchronization.jl
(basically it does a spinning synchronize:
   https://github.com/JuliaGPU/CUDA.jl/blob/08f9c3da46fc5814406cd04c7d4701e641d1722c/lib/cudadrv/synchronization.jl#L77-L97
  and if that fails, blocks on a libuv thread which notifies an event when it wakes up.

Some earlier discussion on discourse:
https://discourse.julialang.org/t/how-to-combine-mpi-non-blocking-isend-irecv-and-julia-tasks/52524/5?u=simonbyrne

**Comment by luraess** [comment]
Thanks for your thoughts @simonbyrne . Indeed, I am interested in having an interface for calling back into task-based runtimes. I am fine with whatever solution, as long as it is performant. (1.) seems to work ok (implemented in our project). (2.) or hybrid could also be a thing as long as spawning or launching a thread is cheap or has no significant overhead. We encountered some perf issues in the CUDA.jl approach where after some spinning, pawning a thread to wait on would result in significant slow-downs.

**Comment by simonbyrne** [comment]
We could always start with a simple spin loop, then switch to a more complicated setup once it is ready. Care to make a pull request?

**Comment by lcw** [comment]
Please make sure there is a way to opt out of nonblocking wait like is done here https://github.com/JuliaGPU/CUDA.jl/blob/c97bc77e4d1c8f36051079dbf12dd3c9bec75eb4/LocalPreferences.toml#L11-L13.

**Comment by simonbyrne** [comment]
My proposal would keep `MPI.Wait` as the blocking version, but define `Base.wait` as the yield-ing version.

**Comment by luraess** [comment]
> We could always start with a simple spin loop, then switch to a more complicated setup once it is ready. Care to make a pull request?

So are you fine with something along the lines of:
```julia
function Base.wait!(req)
    done = false
    while !done
        done, _ = MPI.Test(req, MPI.Status)
        yield()
    end
end
```
as "simple" spin loop? Where specifically should that land in `src`?
